version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot:spring-boot-maven-plugin
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-starter-test
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-starter-json
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-starter
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: io.projectreactor:reactor-test
    versions:
    - 3.4.2
  - dependency-name: io.projectreactor.addons:reactor-extra
    versions:
    - 3.4.2
  - dependency-name: io.projectreactor:reactor-core
    versions:
    - 3.4.2
